Derek furst/multiple components datasets
hubmapconsortium/entity-api pull request #545
Opened 2023-10-09 18:17 UTC by DerekFurstPitt

Implemented datasets/components endpoint to register multiple components from a mult-assay ancestor. These entities are not
created as part of a typical entity creation process. We can't use the normal triggers because those are configured to work with a single ancestor per child dataset. Instead, all of the validation is handled within this endpoint. For activity creation and linkages to the direct ancestor, new functions were created. While, for now, we are only allowing a single parent ancestor, the functions were created such that they would accommodate multiple ancestors. The main difference between this schema function and the existing ones is that it accepts multiple child entities rather than just one. The activity created is of the type Multi-Assay Split

2023-10-10 23:21 UTC, yuanzhou requested changes
@DerekFurstPitt the way you handle this specialized endpoint with mixed use of schema components can be simplified and the SenNet project will appreciate this effort too. I'll describe the steps:

1. First check the required `X-Hubmap-Application` header. And group all the input json validations at the beginning without using any `schema_manager.validate_json_data_against_schema()`. The purpose is to ensure data integrity by checking the required fields and their data values in terms of existence, size, and type...

2. Similar to `create_multiple_samples_details()`, we create two set of IDs (which also validates the `group_uuid` comprehensively) via uuid-api using `schema_manager.create_hubmap_ids()` for the two component datasets. Then build two merged dicts and call `schema_manager.generate_triggered_data()` on each to generate all the dataset node properties via the schema. 

3. As what you've already done, generate one Activity node to be linked to the direct ancestor dataset and the two new component datasets. It's also the time to update the `Activity.creation_action` with the value of "Multi-Assay Split" as you did.

4. Create a similar app neo4j query as `app_neo4j_queries.create_multiple_samples()` and get everything (nodes and relationships) into Neo4j, without using the schema.

5. Add the new datasets to indices via reindex. And return the desired data structure back to ingest-api. Just like what you did.

By following the above approach, we'll have one specialized endpoint that handles the custom json input with custom validations, and one app-specific neo4j query.

2023-10-11 18:30 UTC, yuanzhou commented on src/app.py
> +    require_json(request)
No change needed here. False positive.

2023-10-13 19:35 UTC, maxsibilla approved these changes
I think this addresses the major points that we all discussed. I believe you also addressed all the issues @yuanzhou  mentioned in the card but I will leave that to him to confirm

2023-10-16 15:59 UTC, yuanzhou requested changes
@DerekFurstPitt the rework looks great! In addition to updating the comments to indicate the correct return results, can you also sync the latest `main` into your branch? When I tested locally with your branch, I noticed the dependency issue that had been addressed in `main`.

2023-10-16 15:59 UTC, yuanzhou commented on src/app.py
> +    List of uuids of the newly created component datasets
We are returning two dicts in a list, not just uuids

2023-10-16 15:59 UTC, yuanzhou commented on src/app.py
> +        schema_triggers.set_status_history('status', 'Dataset', user_token, dataset, {})
Good handling of updating the `status_history` by calling the "after_create_trigger" explicitly here!

2023-10-16 15:59 UTC, yuanzhou commented on src/app.py
> +    A list of all the newly generated ids via uuid-api
We are not just returning the ids, please update.

2023-10-16 18:28 UTC, yuanzhou approved these changes

2023-10-16 18:29 UTC, yuanzhou approved these changes

2023-10-16 18:29 UTC, merged