Derek furst/update derived queries
hubmapconsortium/entity-api pull request #559
Opened 2023-10-25 18:22 UTC by DerekFurstPitt

Changed dataset_is_primary to use creation_action to determine whether a dataset is primary rather than inspecting its distance from the nearest sample ancestor

2023-10-27 15:26 UTC, yuanzhou commented
@DerekFurstPitt The query updates handle the "Central Process" and "Lab Process" Activity types. Do we need to exclude the "Multi-Assay Split" type as well for those component datasets?

2023-10-27 16:59 UTC, DerekFurstPitt commented
> @DerekFurstPitt The query updates handle the "Central Process" and "Lab Process" Activity types. Do we need to exclude the "Multi-Assay Split" type as well for those component datasets?

I am uncertain. Issue [534](https://github.com/hubmapconsortium/entity-api/issues/534) only says lab process and central process, and the example query bill included specifically uses the "ends with process" bit

2023-10-27 18:00 UTC, yuanzhou commented
From Bill:
>The result of a “Multi-Assay Split” dataset isn’t a derived/processed dataset so should not be included in this task.

2023-10-27 18:10 UTC, yuanzhou requested changes

2023-10-27 18:10 UTC, yuanzhou commented on src/app_neo4j_queries.py
> +             f" AND NOT toLower(a.creation_action) ENDS WITH 'process'"
The cypher query Bill used in https://github.com/hubmapconsortium/entity-api/issues/534 only finds the derived/processed datasets. However, you are using negation here, so you may need to double check and exclude the “Multi-Assay Split”.

2023-10-31 13:27 UTC, yuanzhou commented on src/app_neo4j_queries.py
> +             f" AND NOT toLower(a.creation_action) ENDS WITH 'process'"
Confirmed with Bill:
>“Multi-Assay Split” datasets are primary datasets.

2023-10-31 13:28 UTC, yuanzhou approved these changes

2023-10-31 14:06 UTC, merged